# Markdown config
markdown: redcarpet
highlighter: rouge
name: WaterBolik
exclude:
- go
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- CONTRIBUTING.md
- ".sass-cache"
- ".ruby-version"
- vendor

permalink: pretty

repos:
- name: waterbolik.github.io
  description: Main repository for the waterbolik.github.io.
  url: https://github.com/waterbolik/waterbolik.github.io

google_analytics_ua: UA-4356815-1

sass:
  sass_dir: assets/_scss
#  style: :compressed

collections:
  visual:
    output: true
    permalink: /:path/
  layout-system:
    output: true
    permalink: /:path/
  elements:
    output: true
    permalink: /:path/
  components:
    output: true
    permalink: /:path/
